### ISSUE TITLE
Insert time as well

### ISSUE THREAD

**Issue by dawnlh** [namikaze-40p/obsidian-date-inserter#2]
Thanks for the convenient plugin! If it could support inserting time in a similar manner, it will be more convenient!

**Comment by namikaze-40p** [comment]
Hi @dawnlh, Thanks for the idea!

I was also initially considering the ability to insert time. But I couldn't come up with an idea to insert as easily as a date.
So I had no choice but to forgo this feature.

If you have any good ideas, I'm willing to consider them.

**Comment by dawnlh** [comment]
Thanks for your quick reply, but I'm not familiar with front-end programming, thus cannot provide useful suggestions. Looking forward to other professional programmers to contribute to the useful feature!

**Comment by namikaze-40p** [comment]
Thanks for reply!

I began to consider a UI to insert time.
But my idea still has a lot to consider.

I hope you will not hold your breath and wait.
