### ISSUE TITLE
Dark mode option

### ISSUE THREAD

**Issue by matisync** [namikaze-40p/obsidian-date-inserter#6]
Hello, thank you for the plugin. Could you add a dark mode option?

**Comment by namikaze-40p** [comment]
Sorry for the late reply, and thanks for the opinion!
I'll see if I can offer the dark mode.

**Comment by namikaze-40p** [comment]
@matisync 
I added new options for color scheme in [v0.3.0](https://github.com/namikaze-40p/obsidian-date-inserter/releases/tag/0.3.0).
You can select the dark mode, try it if you like.

**Comment by namikaze-40p** [comment]
@matisync
Sorry, I have removed the color scheme option because I found the bug.
Instead, I fixed it so that the color scheme follows the Obsidian base theme.

**Comment by matisync** [comment]
![image](https://github.com/namikaze-40p/obsidian-date-inserter/assets/91581285/85ac1b61-d53c-46bc-a8a9-92bbd8b64ce3)

It looks perfectly fine. Thank you!
